### PR TITLE
 Add sloped sprites to walltn32

### PR DESCRIPTION
**Pull request by fidwell**
The next of my sloped wall PRs. As before, these sprites were made by ripping existing sprites and hand-editing in Paint.NET.

Pinging @ZeeMaji for review. This was an easy one though

walltn32

### CODE REVIEW

**Comment by ZeeMaji** [comment]
The sprites themselves look fine to me, but i'm wondering about the usecases for this. specifically non-hacked usecases. I don't think that's too big of a deal for this but it would be nice to know what usecases there are for this outside of hacked parks since official additions (i see these new sloped sprites as another form of official additions) should preferably compliment all aspects of the game.

**Comment by fidwell** [comment]
I hadn't really thought much about it... tbh I don't use this object at all myself, so maybe there is no good use case. I won't be upset if you think this doesn't really fit in and we don't include it.

I'm keeping track of all of these in this ticket: #157 Maybe it'd be good to go through it and see if you have concerns about any of the unfinished walls before I get to them.

**Comment by ZeeMaji** [comment]
In that case i don't really feel like this fits well for official inclusion currently, it doesn't really seem to compliment anything that comes with the game.

As for the others, i'll give my thoughts on them in #157 proper.

**Comment by Gymnasiast** [comment]
I don’t think it would hurt to include these, to be honest, especially considering we’re just adding additional frames to an existing object. I can see it being useful for queue lines, just like some of the others.

**Comment by ZeeMaji** [comment]
When you put it that way, i suppose it would be fine to include.

**Review by Gymnasiast — APPROVED** [review]

**Review by tupaschoal — APPROVED** [review]

**Pull request merged**
