### PR TITLE
fix cursors on TT objects

### PR DESCRIPTION
**Pull request by 733737**
fix cursors to better match WW and Vanilla in TT

solution for https://github.com/OpenRCT2/objects/issues/287

### CODE REVIEW

**Comment by Gymnasiast** [comment]
@ZeeMaji Could you review?

**Comment by 733737** [comment]
some of the FENCE_DOWNs may need to change to HOUSE_DOWNs, but I'm not sure which ones

**Comment by ZeeMaji** [comment]
I'll get to reviewing this, it'll take some time given the amount of objects touched by this PR.

**Comment by 733737** [comment]
you're welcome to change any cursors that are erroneous yourself and come on as co-author

**Comment by 733737** [comment]
After some discussion, we're going to fix this differently than how it's done in my PR

**Pull request closed without merging**
