### PR TITLE
Add sloped sprites to wallbb8, wallbb16, and wallbb32

### PR DESCRIPTION
**Pull request by fidwell**
The next of my sloped wall PRs. As before, these sprites were made by ripping existing sprites and hand-editing in Paint.NET.

Thanks to ZeeMaji for advice.

wallbb8
wallbb16
wallbb32

### CODE REVIEW

**Comment by ZeeMaji** [comment]
Have you tested to ensure they line up correctly with the RCT1 brick terrain edge?

**Comment by fidwell** [comment]
Yeah thanks for reminding me. Hard to tell if they're _perfect_ (they should be) but they're at least pretty dang close:

image

**Comment by ZeeMaji** [comment]
They seem to be off by one pixel vertically from some testing i did, i think they need to be shifted up by one pixel?

**Comment by fidwell** [comment]
For all 3 walls, there is a gap if I shift images 2 and 3 up. But for images 4 and 5 it looked better.

**Comment by ZeeMaji** [comment]
By shift up, i meant the texture of the wall in relation to the full wall sprite so you would just raise the full wall sprite by one pixel before you apply a sloping mask or something. not shifting the sprite's offsets up or down. Kind of hard to explain but i hope that explains it well enough.

For what it's worth, i think it looks mostly fine as it is right now. Just being nit picky as it'd be preferable to get this as good as possible in the initial PR so as to not have to make more changes later on.

**Comment by fidwell** [comment]
I think I get what you mean. I tried shifting up the texture one pixel, but I think it was better before; in this version, it looks like the brick on the seam is too tall.

image

**Comment by ZeeMaji** [comment]
Hmm, odd. Well then in that case i suppose just go with what you had before.

**Pull request merged**
