### PR TITLE
Improve language scripts robustness on command line

### PR DESCRIPTION
**Pull request by tupaschoal**
The scripts only accepts some combinations of switches, so I'm making sure to enforce them.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Can't this be resolved with `ArgumentParser`'s `add_mutually_exclusive_group`?

**Comment by tupaschoal** [comment]
Can they? I don't know, I assumed not because each of the options is already in a mutually exclusive group

**Comment by tupaschoal** [comment]
I tried to, with:
```python
    language_group = parser.add_mutually_exclusive_group(required=True)
    single_input_group = language_group.add_argument_group()
    single_input_group.add_argument('-i', '--input', help='Translation dump file to import from')
    single_input_group.add_argument('-l', '--language', choices=SUPPORTED_LANGUAGES,\
                                    help='Language that is being translated, e.g. ja-JP')
    multi_input_group = language_group.add_argument_group()
    multi_input_group.add_argument('-d', '--dir', type=dir_path,\
                             help='Directory with translation dump files to import from')
    multi_input_group.add_argument('-a', '--all-languages', action='store_true')
```

It doesn't seem to work. I need mutual exclusivity of two groups: `(-l && -i) || (-a && -d)`, but it seems like it isn't possible. I did some research on the web and found some evidence to this conclusion, but posts were fairly old. If you have a hint, I'd happily take it!

**Comment by tupaschoal** [comment]
Yup, I'll rebase soon

**Comment by tupaschoal** [comment]
Rebased

**Pull request merged**
