### PR TITLE
Changes of 4 items in the wrong rct1 tag and the 2 candy "roofs" removal of rct1 tag

### PR DESCRIPTION
**Pull request by TheClaudeQC**
I'm sure that the candy "roofs" wasn't in rct1 at all.

There was the small wooden jurassic fence in Added Attractions.

And there was the 2 circular castle towers and the lily in Loopy Landscapes.

### CODE REVIEW

**Comment by TheClaudeQC** [comment]
This is a re-request, as someone notified that the walls was in Added Attractions

**Review by tupaschoal — COMMENTED** [review]
@Gymnasiast you typically know a lot about these, are you able to confirm the changes are sound?

**Comment by Gymnasiast** [comment]
@tupaschoal I will check them, thanks for asking!

**Review by Gymnasiast — APPROVED** [review]

**Comment by tupaschoal** [comment]
Thank you very much for checking @Gymnasiast !

**Pull request merged**
