### PR TITLE
Add RCT1 corkscrew coaster

### PR DESCRIPTION
**Pull request by spacek531**

### CODE REVIEW

**Comment by spacek531** [comment]
@ZeeMajora

**Review by ZeeMajora — APPROVED** [review]

**Comment by Gymnasiast** [comment]
The difference in artwork between the Car Ride vehicles is so slight that I am very reluctant to merge those.

I might merge the corkscrew and go karts vehicles.

**Comment by ZeeMajora** [comment]
I don't really see the point in anything but an all or nothing approach to the RCT1 vehicles.
First of all where do you draw the line on what gets added and what doesn't? If you draw that at obviously unique vehicles that'd leave vehicles with more subtle but apparent differences out such as the vertical drop trains or the face-off trains.
If you draw it to the point of including those then where do you draw that line exactly? How different do the sprites have to be to be considered "unique enough" for official inclusion?
Even the ones that are the most similar to their RCT2 counterparts are still quite different due to the completely different way these sprites were rendered for RCT1, and i would say they're all different enough to justify official inclusion and it would further bring us towards RCT1 parks looking perfectly accurate in OpenRCT2.

And they can't just be implemented as a graphics asset pack in the future either, many of them have subtle differences with their metadata. Alongside the major issue being that you can't properly map sprites made for 16 rotations to the 32 rotations of RCT2's objects.
Even file size wise they aren't even that big, even before the png graphics are converted to gx and before they're compressed to parkobj zips our whole RCT1 vehicles project only comes in at around 2mb, for comparison all of the vehicles in the official folder come in at around 2mb as well and that's after the compression process.
In terms of end user confusion i feel like our current filter system works fine if the rct1 source games are removed from the rct2 objects that have rct1 counterparts introduced, if it really is deemed "too confusing" then we could just introduce the much discussed compatibility object flag that will hide them by default but i really doubt that'd be needed.

Really, can you give us more reasons for not adding all of them beyond "the artwork difference is too minor"? That alone isn't convincing me and i can't think of any other reasons to not add all of the RCT1 vehicles.

**Comment by spacek531** [comment]
The OpenRCT2 source code is the sole arbiter of how RCT1 parks are imported into OpenRCT2. A decision against including RCT1 rides with unique sprites is a decision toward a fork where they *are* included.

It's often said to whiners, "if you want it so bad do it yourself." So we are doing it ourselves, because we want to improve OpenRCT2's compatibility with RCT1. We aren't content to sit on our laurels and say "only the obvious differences are necessary." The fact is that aside from animated boat rides, RCT1 rides are different than RCT2 rides.

We have been working on this for months, and it would be a cruelty to deny this project on the grounds you've explained.

**Comment by Gymnasiast** [comment]
> The OpenRCT2 source code is the sole arbiter of how RCT1 parks are imported into OpenRCT2. A decision against including RCT1 rides with unique sprites is a decision toward a fork where they are included.

If you think I’m willing to reconsider my position if you start issuing threats, you’re sorely mistaken.

> We have been working on this for months, and it would be a cruelty to deny this project at this stage.

So we should just merge anything anyone has been working on for months? I have never promised to merge everything. In fact, I have very deliberately asked for PRs on a vehicle-by-vehicle basis.

**Comment by ZeeMajora** [comment]
=== For me, that is a pretty convincing reason on its own. Spacek’s screenshot shows quite clearly that the cars are almost the same, except the RCT2 counterpart have better shading.

Couldn't you say the same thing about the RCT1 footpath surface objects already in the repo? All of the non-tile footpath surfaces are nearly identical to their RCT2 counterparts asides from the slopes instead of stairs and sqaured corners instead of rounded corners on the dirt surfaces.
If you applied your logic here to the footpath surfaces then we should only have the 4 tile surfaces as they're entirely unique to RCT1 and the others are "too similar" to what's in RCT2 even despite their subtle differences.
I would say the vehicles in spacek's screenshot have far more differences than the footpath surfaces or are at the very least on the same level as them in terms of being similar to their RCT2 counterparts.

Really, what is even the point of including the all of the RCT1 footpath surfaces/railings, terrain surfaces/edges, but only a select few cherry picked rides that are deemed to be "unique enough" despite many of their subtle differences being on the same level as many already included objects.
Why even include anything that isn't blatantly obvious surface level RCT1 exclusive content such as the tile path surfaces and the cut terrain textures and the entirely exclusive vehicle designs? Just that little bit would probably satisfy 90% of the OpenRCT2 userbase.
90% of people playing OpenRCT2 probably didn't know about the footpath surfaces having slopes in RCT1 instead of stairs, the green tarmac being a subtly different shade of green, the fact that the single person swinging cars existed at all, the fact that the classic wooden rc was a separate ride type. I'd reckon most people probably haven't even noticed them since they've been reintroduced at all.

Like spacek said, the current approach is just simply going to leave OpenRCT2's RCT1 compatibility with a glaring empty void in it for a really arbitrary reason that is trying to appeal to people who probably don't even care much about OpenRCT2's RCT1 compatibility in the first place.
If you're going to go this far with RCT1 content parity to the point where we have a wooden fence scenery wall that is LITERALLY IDENTICAL to it's closest RCT2 counterpart at one of the two angles of it's sprites then i don't see why the vehicles with a completely different style and sometimes subtly different design from their RCT2 counterparts are such a big deal to include.

=== Cluttering up of the object list with objects that are exactly the same to almost every user except perhaps people like us.

For the object list becoming "cluttered" i already mentioned i don't believe that would be a problem with our current filtering system.

If you really feel like it would be a problem then like i also said the "too similar" objects could just be hidden by the much discussed compatibility object flag once/if that is implemented which would hide the objects from more novice users.

=== Track designs will give a lot more warnings about missing vehicles.

I fail to see how track design vehicle warnings are that major of an issue to use them as an argument against including the RCT1 vehicles, i would consider them a minor annoyance at the most.
If you really think this is a major issue then couldn't we just do something similar to what we already do with the footpath objects and remap them based on what objects are currently enabled if the original object isn't available?

=== (This one is subjective, but: ) RCT1 parks will look worse than necessary, as RCT1 graphics are just a bit less refined than RCT2’s (see the point about shading I made earlier).

You did say it's subjective but i feel like the current approach just makes the art style in RCT1 parks more inconsistent than anything, are RCT1's graphics less refined than RCT2's? Yes, but they have their own art style that is pretty distinct from RCT2's art style.
Your current approach is just going to result in a mish mash of the two different art styles depending on what vehicles are implemented and which ones are not, it's not quite as bad as the RCT2 expansions but at the end of the day it's still going to be inconsistent which is still going to just look bad to some people.
I think this would end up making RCT1 parks looking worse in the long run than if you just simply used RCT1 or RCT2 vehicles for everything as the majority of them will be in RCT2's more refined art style with there being a few oddball ones that are in RCT1's quite different art style and would look out of place more than anything.

**Comment by Gymnasiast** [comment]
I fail to see how the current situation leaves a glaring void when even having the two cars side-by-side shows only a slight difference. As I see it, the only glaring void are the missing Spinning Cars. And possibly the Corkscrew RC and Go Karts.

Also, if the idea is that having RCT1 ports for _all_ vehicles makes it more consistent, then we are still putting them on tracks with RCT2 artwork, with supports that look slightly different (in terms of artwork, not counting the fact that RCT2 renders them in fewer places than RCT1). You’re never going to get a pixel-perfect replica of how RCT1 renders. So drawing the line at vehicles that actually look different is no more arbitrary than drawing it at all the vehicles.

**Comment by ZeeMajora** [comment]
> Also, if the idea is that having RCT1 ports for all vehicles makes it more consistent, then we are still putting them on tracks with RCT2 artwork, with supports that look slightly different (in terms of artwork, not counting the fact that RCT2 renders them in fewer places than RCT1).

Most of the RCT2 track sprites are the same as their RCT1 counterparts to the point where it's one of the most useful things when it comes to remaking RCT1 thumbnails for our project. Asides from the shallow banking of the stand-up coaster which i would consider a separate thing the only track sprites that are different from what i recall are the bobsleigh track and banking turn sprites for the wooden twister coasters. Those and the support sprite differences are very subtle even to me and they're still in the same art style between the two games so i wouldn't say it's as important as the vehicles for the presentation of RCT1 parks.
Plus that stuff can just be tuned by the user in the future with a graphics asset pack, the same cannot be said for the vehicles as you cannot properly map sprites meant for 16 rotations to 32 rotations alongside their various subtle metadata differences as i mentioned earlier.

> You’re never going to get a pixel-perfect replica of how RCT1 renders. So drawing the line at vehicles that actually look different is no more arbitrary than drawing it at all the vehicles.

We're already very close to that already, i see the remaining vehicles as one of the last cherries for the top of the rct1 compatibility cake so to speak. I don't see what the point of just stopping at 95% accuracy is when we could reach for 99%.

How is adding all of them no more arbitrary than adding only some of them? There's a precedent for adding all of another type of RCT1 object in the footpath surfaces with their extremely subtle differences to their RCT2 counterparts so i don't see why the ride objects should be treated any differently from those.

**Comment by spacek531** [comment]
> > The OpenRCT2 source code is the sole arbiter of how RCT1 parks are imported into OpenRCT2. A decision against including RCT1 rides with unique sprites is a decision toward a fork where they are included.
> 
> If you think I’m willing to reconsider my position if you start issuing threats, you’re sorely mistaken.

This was poorly worded. Not including the vehicles with no recourse is divisive.

> > We have been working on this for months, and it would be a cruelty to deny this project at this stage.

> So we should just merge anything anyone has been working on for months? I have never promised to merge everything. In fact, I have very deliberately asked for PRs on a vehicle-by-vehicle basis.

In our discussions on discord you made it appear you were open to being convinced. Either Majora is a poor orator or you were not open to being convinced.

**Comment by Gymnasiast** [comment]
> In our discussions on discord you made it appear you were open to being convinced. Either Majora is a poor orator or you were not open to being convinced.

Or you are grossly oversimplifying the situation and turning it into a false dilemma and an ad hominem. We accept an enormous amount of backtalk and discussion, much more so than almost every other open source project, but I do not want to argue with someone who is very hostile to me and does not want to conduct a courteous discussion.

**Comment by spacek531** [comment]
I apologize. I'm letting my emotions get the better of me and I'm a poor writer on top.

**Comment by SpartanFrederic104** [comment]
Anyway, wasn't there a reversed version of the RCT1 corkscrew coaster train in the RCT1Vehicles repo? I saw it wasn't included here. Maybe for a future PR perhaps?

**Comment by Gymnasiast** [comment]
Ok thanks. I’m not holding a grudge.

**Comment by ZeeMajora** [comment]
> Anyway, wasn't there a reversed version of the RCT1 corkscrew coaster train in the RCT1Vehicles repo? I saw it wasn't included here. Maybe for a future PR perhaps?

The reversed corkscrew is a custom creation for our repo along with the open cars american steam trains, it's not from RCT1 and probably should not be included officially as such.

**Comment by SpartanFrederic104** [comment]
@ZeeMajora Oh, now that clarifies it.

**Comment by spacek531** [comment]
I was not aware that you wanted only one ride at a time. This PR is now only for the corkscrew coaster.

**Comment by 733737** [comment]
Not that anyone asked, but imo, the more the merrier! I don't see the harm in bringing these vehicles to openrct2. Also, the reversed corkscrew coaster imo could be added to the game, surely the hybrid coaster and single rail weren't in vanilla rct2, but you added them. I think being a more "open" openrct2 would be great! The players of openrct2 would love open steam trains as well, and I think the goal of the project shouldn't necessarily be to add a gigabyte of custom scenery and rides, but maybe just tactful additions here and there, like you've been doing with the rooves ;)

**Comment by Gymnasiast** [comment]
By the way, when can we expect the Spinning Cars for the Classic Mini? That’s currently the biggest missing thing, much bigger than any other vehicle type IMO.

**Comment by spacek531** [comment]
> By the way, when can we expect the Spinning Cars for the Classic Mini? That’s currently the biggest missing thing, much bigger than any other vehicle type IMO.

I have to refactor the paint code for spinning rides first, I've been slowly working on it.

**Pull request merged**
